CREATE TABLE IF NOT EXISTS harddisk_claim_returns (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    return_no VARCHAR(30) NOT NULL,
    delivery_request_id INT UNSIGNED NULL,
    request_no VARCHAR(50) NULL,
    main_branch_code VARCHAR(10) NOT NULL,
    branch_code VARCHAR(50) NOT NULL,
    branch_name VARCHAR(255) NOT NULL,
    hdd_serial VARCHAR(100) NOT NULL,
    claim_reason VARCHAR(255) NOT NULL,
    hdd_condition VARCHAR(255) NULL,
    return_tracking_no VARCHAR(100) NULL,
    received_by VARCHAR(255) NOT NULL,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'received',
    sent_claim_at DATETIME NULL,
    claim_result VARCHAR(255) NULL,
    remark TEXT NULL,
    created_by VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NULL,
    updated_at DATETIME NULL DEFAULT NULL,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_return_no (return_no),
    KEY idx_branch_code (branch_code),
    KEY idx_main_branch_code (main_branch_code),
    KEY idx_hdd_serial (hdd_serial),
    KEY idx_status (status),
    KEY idx_received_at (received_at),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
