CREATE TABLE IF NOT EXISTS `toner_issue_reports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `issue_no` VARCHAR(30) NOT NULL,
  `main_branch_code` VARCHAR(20) NOT NULL,
  `branch_code` VARCHAR(50) NOT NULL,
  `main_branch_name` VARCHAR(255) NOT NULL,
  `branch_name` VARCHAR(255) NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `symptom` VARCHAR(1000) NOT NULL,
  `printer_serial` VARCHAR(120) NOT NULL,
  `reported_date` DATE NOT NULL,
  `reported_by` VARCHAR(255) NOT NULL,
  `reported_by_employee_code` VARCHAR(50) DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'reported',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_toner_issue_reports_issue_no` (`issue_no`),
  KEY `idx_toner_issue_reports_branch_code` (`branch_code`),
  KEY `idx_toner_issue_reports_main_branch_code` (`main_branch_code`),
  KEY `idx_toner_issue_reports_reported_date` (`reported_date`),
  KEY `idx_toner_issue_reports_status` (`status`),
  KEY `idx_toner_issue_reports_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
