CREATE TABLE IF NOT EXISTS `server` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `server_name` VARCHAR(150) NOT NULL,
  `dns_name` VARCHAR(150) NULL,
  `serial_mt` VARCHAR(150) NULL,
  `processor` VARCHAR(150) NULL,
  `memory_size` VARCHAR(80) NULL,
  `memory_type` VARCHAR(80) NULL,
  `disk_size` VARCHAR(80) NULL,
  `disk_type` VARCHAR(80) NULL,
  `caretaker` VARCHAR(150) NULL,
  `location` VARCHAR(150) NULL,
  `expire_date` DATE NULL,
  `created_by` VARCHAR(150) NULL,
  `updated_by` VARCHAR(150) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_server_name` (`server_name`),
  KEY `idx_dns_name` (`dns_name`),
  KEY `idx_expire_date` (`expire_date`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
