CREATE TABLE IF NOT EXISTS `notebook` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `receiver_employee_code` VARCHAR(50) NOT NULL,
  `sn_notebook` VARCHAR(120) NOT NULL,
  `device_user_name` VARCHAR(180) NOT NULL,
  `department` VARCHAR(180) NULL,
  `office_email` VARCHAR(180) NULL,
  `office_email_password` VARCHAR(255) NULL,
  `office_key` VARCHAR(255) NULL,
  `po_no` VARCHAR(120) NULL,
  `recorded_date` DATE NULL,
  `created_by` VARCHAR(180) NULL,
  `updated_by` VARCHAR(180) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_receiver_employee_code` (`receiver_employee_code`),
  KEY `idx_sn_notebook` (`sn_notebook`),
  KEY `idx_device_user_name` (`device_user_name`),
  KEY `idx_department` (`department`),
  KEY `idx_office_email` (`office_email`),
  KEY `idx_recorded_date` (`recorded_date`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
